### ISSUE TITLE
v3: stateless block verifier -> block verifier

### ISSUE THREAD

**Issue by lightsing** [scroll-tech/stateless-block-verifier#52]
In the next release, I propose implementing a **stateful** verifier to complement the existing stateless mode.
This enhancement would allow us to verify an entire blockchain from the genesis block to the latest block using only the `eth_getBlockByNumber` RPC call, which is significantly more cost-effective than using `scroll_getBlockTraceByNumberOrHash`.

The repository will support both stateless and stateful verification modes, providing more comprehensive testing capabilities across different networks.
By leveraging `eth_getBlockByNumber`, we reduce the need for expensive trace-based methods (`scroll_getBlockTraceByNumberOrHash`), resulting in faster full chain verification.

**Comment by lispc** [comment]
btw we can choose to assert state root every N block.  To reduce trie commitment cost.

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by lispc** [comment]
done
